name: Build Custom Database

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  build_db:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DB_ID: bios_db

    steps:
    - name: Install apt-get utilities
      run: sudo apt-get install detox sharutils

    - uses: actions/checkout@v2
    - uses: fregante/setup-git-user@v2

    - name: Build Custom Database for MiSTer Downloader
      run: set -o pipefail && curl --fail --location https://raw.githubusercontent.com/theypsilon/Downloader_DB-Template_MiSTer/main/.github/build_db.py | python3 -

    - name: Add NeoGeo UniBios
      run: |
        if [ ! -f db.json ]; then exit 0; fi

        python3 .github/add_neogeo_unibios.py
        git add bios_db.json bios_db.json.zip
        git commit -m "Creating bios_db DB"
        git push --force origin db
